### ISSUE TITLE
[Menu Feature 2] Game Creation and File Reading

### ISSUE THREAD

**Issue by jchenDDD** [CSC207-2022F-UofT/course-project-rogue#10]
This feature occurs once the program of the game gets started(In main while the structure of the MVC architecture is being set up).
- GameFileReader reads the file and converts the data into data structures(List, integer, etc.) that can be used.
- File stores player & monster starting stats, item stats(attack power, healing points, etc.), the map grid containing location of events.

**Comment by villanueva-j** [comment]
Completed
