### ISSUE TITLE
[Gameplay feature 2] Earning Items

### ISSUE THREAD

**Issue by littlepeach17** [CSC207-2022F-UofT/course-project-rogue#4]
Allows the user to earn Items in the form of Collectibles or Equipment.

- obtaining weapon Equipment increases the Player's attack power
- obtaining armour Equipment reduces damage received by the Player
- essence Collectibles allow the Player to upgrade and heal
- artifact Collectibles count toward the number of collectibles the Player needs to win the game

**Comment by villanueva-j** [comment]
Closing because Item classes and ArtifactEvent/EssenceEvent are implemented.
