### ISSUE TITLE
[Gameplay Feature 3] Player

### ISSUE THREAD

**Issue by stalight** [CSC207-2022F-UofT/course-project-rogue#5]
Allows the existence of a player avatar for the user in the game.

Responsibilities:

- Saves Player Location
- Contains Max health and Current Health
- Contains Player Inventory
- Contains Player's base attack strength
- Can get all the values above and change most of them as needed
- Allow the change of equipment and the change of Collectibles within its inventory

**Comment by villanueva-j** [comment]
Closing since Player class is completed
